name: HelloWorld
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "15.0"
targets:
  HelloWorld:
    type: application
    platform: iOS
    sources:
      - HelloWorld
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        PRODUCT_BUNDLE_IDENTIFIER: com.example.HelloWorld
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1"
